### ISSUE TITLE
License reference in pom.xml

### ISSUE THREAD

**Issue by dabla** [wblancqu/actress#3]
The pom contains a reference to the GNU license but the project contains the Apache 2.0 license.  I suppose the pom should be modified to reference the Apache 2.0 license?

Like this:

<licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

**Comment by wblancqu** [comment]
Feel free to adapt and contribute ;-)

**Comment by wblancqu** [comment]
Thanks!

**Comment by wblancqu** [comment]
Created a release 1.2 with updated embedded license.
