### ISSUE TITLE
Add actress to CI in the cloud

### ISSUE THREAD

**Issue by dabla** [wblancqu/actress#4]
It would be cool to build actress in the cloud on: [https://travis-ci.org/](https://travis-ci.org/)

You could then add a build status in the ReadMe file:

`[![Build Status](https://travis-ci.org/wblancqu/actress.svg?branch=master)](https://travis-ci.org/wblancqu/actress)`

Finally just add a .travis.yml file containing:

```
language: java
jdk: openjdk6
```

**Comment by wblancqu** [comment]
Cool stuff, didn't know about that one. Thanks for sharing!
